"""Sheet layout: reference image + bubble geometry.

Bubble positions are NOT hard-coded here: they are generated by OMRChecker's own
``Template`` / ``FieldBlock`` classes from ``config/template.json`` (standard OMRChecker
template format), so the same template can also be used with the original CLI.
"""
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Tuple

import cv2
import numpy as np

from omr_app.imaging import render_pdf_page

log = logging.getLogger("omr_app.layout")


@dataclass
class BubbleSpec:
    question: int  # 1-based question number
    option: str  # "A".."D"
    center: Tuple[float, float]  # reference pixel coords


@dataclass
class SheetLayout:
    sheet_id: str
    dpi: float
    ref_gray: np.ndarray  # reference (blank sheet) rendered at `dpi`
    bubbles: List[BubbleSpec]
    options: List[str]
    num_questions: int
    roi_radius_px: int
    patch_half_px: int
    hole_mask: np.ndarray  # bool (2*patch_half+1)^2 centred: paper inside the printed 'O'
    outer_mask: np.ndarray  # bool, bubble disk outside the printed 'O'
    probe_mask: np.ndarray  # bool, annulus outside the 'O' used for tick/cross detection
    probe_bins: np.ndarray  # int angular bin index per pixel
    stroke_bins: int
    glyph_patch: np.ndarray  # uint8 reference patch around an empty bubble (template for matching)
    answer_area_px: Tuple[int, int, int, int]
    fields_px: Dict[str, dict] = field(default_factory=dict)

    @property
    def size(self):
        h, w = self.ref_gray.shape[:2]
        return w, h

    def pt_to_px(self, v):
        return v * self.dpi / 72.0

    def bubbles_by_question(self):
        out = {}
        for b in self.bubbles:
            out.setdefault(b.question, []).append(b)
        return out


def _omrchecker_bubbles(template_path: Path, options, prefix):
    """Parse the OMRChecker template.json with OMRChecker's own Template class."""
    from src.defaults import CONFIG_DEFAULTS
    from src.template import Template

    template = Template(Path(template_path), CONFIG_DEFAULTS)
    page_w, page_h = template.page_dimensions
    specs = []
    for block in template.field_blocks:
        bw, bh = block.bubble_dimensions
        for field_bubbles in block.traverse_bubbles:
            for bubble in field_bubbles:
                label = bubble.field_label
                if not label.startswith(prefix) or bubble.field_value not in options:
                    continue
                q = int(label[len(prefix):])
                specs.append(BubbleSpec(q, bubble.field_value, (bubble.x + bw / 2.0, bubble.y + bh / 2.0)))
    specs.sort(key=lambda s: (s.question, options.index(s.option)))
    return specs, (page_w, page_h)


def load_layout(sheet_cfg: dict) -> SheetLayout:
    cfg_dir = Path(sheet_cfg["_dir"])
    ref = sheet_cfg["reference"]
    dpi = float(ref["dpi"])
    ref_gray = render_pdf_page(cfg_dir / ref["pdf"], ref.get("page", 1) - 1, dpi)
    h, w = ref_gray.shape

    options = list(sheet_cfg["questions"]["options"])
    nq = int(sheet_cfg["questions"]["count"])
    specs, (tw, th) = _omrchecker_bubbles(
        cfg_dir / sheet_cfg["omr_template"], options, sheet_cfg["questions"].get("field_label_prefix", "q")
    )
    if (tw, th) != (w, h):
        raise ValueError(
            f"template pageDimensions {tw}x{th} do not match reference render {w}x{h} at {dpi} DPI"
        )
    if len(specs) != nq * len(options):
        raise ValueError(f"template defines {len(specs)} bubbles, expected {nq * len(options)}")

    to_px = dpi / 72.0
    bcfg = sheet_cfg["bubble"]
    roi_r = int(round(bcfg["roi_radius_pt"] * to_px))
    half = int(round(bcfg["patch_half_size_pt"] * to_px))

    # Glyph geometry from the first bubble (all glyphs are identical in the PDF):
    #   hole  = paper inside the printed 'O' (the most reliable "filled?" signal)
    #   outer = bubble area outside the printed 'O' up to roi_radius (ink spilling over)
    #   the printed ring itself (always dark) is excluded from both.
    cx, cy = (int(round(v)) for v in specs[0].center)
    patch = ref_gray[cy - half: cy + half + 1, cx - half: cx + half + 1].copy()
    ink = (patch < bcfg.get("glyph_ink_threshold", 140)).astype(np.uint8)
    _, lab = cv2.connectedComponents(1 - ink, connectivity=4)
    hole = (lab == lab[half, half]) & (lab != lab[0, 0])
    if not hole.any():
        raise ValueError("printed bubble glyph has no inner hole - check reference/template")
    solid_glyph = (ink > 0) | hole
    d = int(bcfg.get("glyph_dilate_px", 1))
    k = np.ones((2 * d + 1, 2 * d + 1), np.uint8)
    hole_mask = cv2.erode(hole.astype(np.uint8), k) > 0 if d > 0 else hole
    glyph_outer = cv2.dilate(solid_glyph.astype(np.uint8), k) > 0 if d > 0 else solid_glyph
    yy, xx = np.mgrid[-half: half + 1, -half: half + 1]
    disk = (xx * xx + yy * yy) <= roi_r * roi_r
    outer_mask = disk & ~glyph_outer
    if not bcfg.get("exclude_printed_glyph", True):
        hole_mask, outer_mask = disk & (xx * xx + yy * yy <= (roi_r // 2) ** 2), disk
    # stroke probe: annulus outside the printed 'O', split into angular bins. Ticks / crosses
    # leave thin "spokes" here, real fills cover it broadly (or not at all).
    probe_r = int(round(bcfg["stroke_probe_radius_pt"] * to_px))
    if probe_r > half:
        raise ValueError("stroke_probe_radius_pt must be <= patch_half_size_pt")
    probe_mask = ((xx * xx + yy * yy) <= probe_r * probe_r) & ~glyph_outer
    nb = int(bcfg["stroke_bins"])
    probe_bins = ((np.arctan2(yy, xx) + np.pi) / (2 * np.pi) * nb).astype(int) % nb

    # Sanity: every template bubble must sit on a printed glyph in the reference (within 1.5 px).
    m = 2
    for s in specs:
        x, y = (int(round(v)) for v in s.center)
        p = ref_gray[y - half - m: y + half + m + 1, x - half - m: x + half + m + 1]
        res = cv2.matchTemplate(p, patch, cv2.TM_CCOEFF_NORMED)
        _, score, _, loc = cv2.minMaxLoc(res)
        if score < 0.8 or max(abs(loc[0] - m), abs(loc[1] - m)) > 1:
            raise ValueError(f"template bubble Q{s.question}{s.option} at {s.center} is not on a printed bubble "
                             f"(match {score:.2f}, offset {loc[0] - m},{loc[1] - m})")

    ax0, ay0, ax1, ay1 = (int(round(v * to_px)) for v in sheet_cfg["answer_area_pt"])
    fields = {
        name: {"label": f.get("label", name), "rect_px": [int(round(v * to_px)) for v in f["rect_pt"]]}
        for name, f in sheet_cfg.get("fields", {}).items()
    }
    log.debug("layout loaded: %d bubbles, ref %dx%d @ %.0f dpi, hole=%dpx outer=%dpx",
              len(specs), w, h, dpi, hole_mask.sum(), outer_mask.sum())
    return SheetLayout(
        sheet_id=sheet_cfg.get("sheet_id", "sheet"),
        dpi=dpi,
        ref_gray=ref_gray,
        bubbles=specs,
        options=options,
        num_questions=nq,
        roi_radius_px=roi_r,
        patch_half_px=half,
        hole_mask=hole_mask,
        outer_mask=outer_mask,
        probe_mask=probe_mask,
        probe_bins=probe_bins,
        stroke_bins=nb,
        glyph_patch=patch,
        answer_area_px=(ax0, ay0, ax1, ay1),
        fields_px=fields,
    )

